insert into `htmlformentry_html_form` ( `form_id`, `name`, `xml_data`, `creator`,
            `date_created`, `changed_by`, `date_changed`, `retired`, `uuid`, `description`,
            `retired_by`, `date_retired`, `retire_reason`) values('299', NULL, '<htmlform formUuid="64158ec1-0882-496d-ab77-59c1c0471a40" formName="Transit Program Enrolment"
                formEncounterType="29d2c105-ef5d-465b-9473-858ea678f794" formVersion="1.0"> <!--
                Autogenerated example form  (template from 07-June-2025 --> <macros>
            paperFormId = (Fill this in) headerColor =#009d8e fontOnHeaderColor = white </macros>
             <style> .section { border: 1px solid $headerColor; padding:
                    2px; text-align: left; margin-bottom: 1em; } .show{ display:
            none; } .sectionHeader { background-color: $headerColor; color:
            $fontOnHeaderColor; display: block; padding: 2px; font-weight: bold;
            } table.baseline-aligned td { vertical-align: baseline; } .button.app,
            button.app, input[type="submit"].app, input[type="button"].app,
            input[type="submit"].app, a.button.app { width: 140px !important; } </style>
             <script type="text/javascript"> jQuery(document).ready(function ($) { var
            getUrl =
                    window.location; var baseUrl = getUrl .protocol + "//" + getUrl.host +
            "/" +
                    getUrl.pathname.split(\'/\')[1]; var domain =
            getUrl.pathname.split(\'/\')[1]; $.urlParam = function(name){ var results =
            new RegExp(\'[\\?&amp;]\' + name + \'=([^&amp;#]*)\').exec(window.location.href); if
            (results==null){ return null; } else{ return decodeURI(results[1]) ||
            0; } } 
            href_carecard=baseUrl+"/htmlformentryui/htmlform/enterHtmlFormWithStandardUi.page?patientId="+$.urlParam(\'patientId\')+"&amp;visitId="+$.urlParam(\'visitId\')+"&amp;formUuid=5d522e63-463e-4a9f-a2c1-7ebbe4069a49&amp;returnUrl=%2F"+domain+"%2Fcoreapps%2Fclinicianfacing%2Fpatient.page%3FpatientId%3D"+$.urlParam(\'patientId\')+"%26"
            href_lab=baseUrl+"/htmlformentryui/htmlform/enterHtmlFormWithStandardUi.page?patientId="+$.urlParam(\'patientId\')+"&amp;visitId="+$.urlParam(\'visitId\')+"&amp;formUuid=029e5be3-051b-40cd-a578-a7bf33ade676&amp;returnUrl=%2F"+domain+"%2Fcoreapps%2Fclinicianfacing%2Fpatient.page%3FpatientId%3D"+$.urlParam(\'patientId\')+"%26"
            href_pharm=baseUrl+"/htmlformentryui/htmlform/enterHtmlFormWithStandardUi.page?patientId="+$.urlParam(\'patientId\')+"&amp;visitId="+$.urlParam(\'visitId\')+"&amp;formUuid=4a238dc4-a76b-4c0f-a100-229d98fd5758&amp;returnUrl=%2"+domain+"%2Fcoreapps%2Fclinicianfacing%2Fpatient.page%3FpatientId%3D"+$.urlParam(\'patientId\')+"%26"
              var care = $(\'#carecard\')
            care.attr("href",href_carecard) var la = $(\'#lab\')
            la.attr("href",href_lab) var ph = $(\'#pharm\')
            ph.attr("href",href_pharm) }); </script> <table
                    class="baseline-aligned"> <tr>
                        <td>Transit Program Enrolment</td>
                    </tr> <tr> <td>
             <div id="home-container"> <div id="apps">  <a id="pharm" 
                                        href="/baseUrl/htmlformentryui/htmlform/enterHtmlFormWithStandardUi.page?patientId=&amp;visitId=&amp;formUuid=1ae18e30-31c6-4daf-87f2-6075d0a0b2df&amp;returnUrl=%2F+domain+%2Fcoreapps%2Fclinicianfacing%2Fpatient.page%3FpatientId%3Db050b4b9-6786-4e69-93b6-82b641cc4fc0%26encounterId%3D1242%26encounterId%3D1258%26"
                                        
                                        class="button app big art"
                                        target="_blank"> <i class="icon-sort"></i>
            Pharmacy Order </a>  <a id="carecard" 
                                        href="/baseUrl/htmlformentryui/htmlform/enterHtmlFormWithStandardUi.page?patientId=&amp;visitId=&amp;formUuid=5d522e63-463e-4a9f-a2c1-7ebbe4069a49&amp;returnUrl=%2F+domain+%2Fcoreapps%2Fclinicianfacing%2Fpatient.page%3FpatientId%3Db050b4b9-6786-4e69-93b6-82b641cc4fc0%26encounterId%3D1242%26encounterId%3D1258%26"
                                         class="button app big art" target="_blank">   <i
                                            class= "icon-truck"></i> Care Card </a> <a id= "lab" 
                                        href="/baseUrl/htmlformentryui/htmlform/enterHtmlFormWithStandardUi.page?patientId=&amp;visitId=&amp;formUuid=029e5be3-051b-40cd-a578-a7bf33ade676&amp;returnUrl=%2F+domain+%2Fcoreapps%2Fclinicianfacing%2Fpatient.page%3FpatientId%3Db050b4b9-6786-4e69-93b6-82b641cc4fc0%26encounterId%3D1242%26encounterId%3D1258%26"
                                         class="button app big art" target="_blank"> <i
                                            class="icon-truck"></i> Lab forms </a>
             </div> </div> </td> </tr> </table> </htmlform>','1','2025-06-07
            17:15:31','1','2025-06-07
            17:32:21','0','45aed573-82b7-4528-aa5b-f5f4de9dc803',NULL,NULL,NULL,NULL);